# Build Delve
FROM golang:1.18
ADD . /api
WORKDIR /api
RUN go install github.com/go-delve/delve/cmd/dlv@latest
RUN go build -gcflags="all=-N -l" -o /api/app /api/internal/cmd/main.go
CMD ["/go/bin/dlv", "--listen=:2345", "--headless=true", "--api-version=2", "--accept-multiclient", "--continue=true", "exec" , "/api/app"]
EXPOSE 8080 2345