apiVersion: v1
kind: Service
metadata:
  name: go-web-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: debug
    port: 2345
    targetPort: 2345
  selector:
    name: go-web-app